/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CellphoneValidationDto } from '../models';
import { UnauthorizedTokenDto } from '../models';
/**
 * CellphoneApi - axios parameter creator
 * @export
 */
export const CellphoneApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CellphoneValidationDto} body 
         * @param {string} authorization Custom header
         * @param {string} apikey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validate: async (body: CellphoneValidationDto, authorization: string, apikey: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling validate.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling validate.');
            }
            // verify required parameter 'apikey' is not null or undefined
            if (apikey === null || apikey === undefined) {
                throw new RequiredError('apikey','Required parameter apikey was null or undefined when calling validate.');
            }
            const localVarPath = `/api/cellphone/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            if (apikey !== undefined && apikey !== null) {
                localVarHeaderParameter['apikey'] = String(apikey);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CellphoneApi - functional programming interface
 * @export
 */
export const CellphoneApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CellphoneValidationDto} body 
         * @param {string} authorization Custom header
         * @param {string} apikey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validate(body: CellphoneValidationDto, authorization: string, apikey: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await CellphoneApiAxiosParamCreator(configuration).validate(body, authorization, apikey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CellphoneApi - factory interface
 * @export
 */
export const CellphoneApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {CellphoneValidationDto} body 
         * @param {string} authorization Custom header
         * @param {string} apikey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validate(body: CellphoneValidationDto, authorization: string, apikey: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return CellphoneApiFp(configuration).validate(body, authorization, apikey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CellphoneApi - object-oriented interface
 * @export
 * @class CellphoneApi
 * @extends {BaseAPI}
 */
export class CellphoneApi extends BaseAPI {
    /**
     * 
     * @param {CellphoneValidationDto} body 
     * @param {string} authorization Custom header
     * @param {string} apikey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CellphoneApi
     */
    public async validate(body: CellphoneValidationDto, authorization: string, apikey: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return CellphoneApiFp(this.configuration).validate(body, authorization, apikey, options).then((request) => request(this.axios, this.basePath));
    }
}
