/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AssignToMeDto
 */
export interface AssignToMeDto {

    /**
     * @type {number}
     * @memberof AssignToMeDto
     * @example 1
     */
    userId: number;

    /**
     * @type {number}
     * @memberof AssignToMeDto
     * @example 1
     */
    branchId: number;
}
