/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WhatsappContactDto } from './whatsapp-contact-dto';
 /**
 * 
 *
 * @export
 * @interface ContactsResponseDTO
 */
export interface ContactsResponseDTO {

    /**
     * @type {Array<WhatsappContactDto>}
     * @memberof ContactsResponseDTO
     */
    data: Array<WhatsappContactDto>;
}
