/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2011Message } from './inline-response2011-message';
import { KeyDto } from './key-dto';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2011Class
 */
export interface InlineResponse2011Class {

    /**
     * @type {KeyDto}
     * @memberof InlineResponse2011Class
     */
    key: KeyDto;

    /**
     * @type {string}
     * @memberof InlineResponse2011Class
     * @example Jhon Doe
     */
    pushName: string;

    /**
     * @type {string}
     * @memberof InlineResponse2011Class
     * @example PENDING
     */
    status: string;

    /**
     * @type {InlineResponse2011Message}
     * @memberof InlineResponse2011Class
     */
    message: InlineResponse2011Message;

    /**
     * @type {any}
     * @memberof InlineResponse2011Class
     */
    contextInfo: any;

    /**
     * @type {string}
     * @memberof InlineResponse2011Class
     * @example conversation
     */
    messageType: string;

    /**
     * @type {number}
     * @memberof InlineResponse2011Class
     * @example 1738267884
     */
    messageTimestamp: number;

    /**
     * @type {string}
     * @memberof InlineResponse2011Class
     * @example e2845cfb-00e4-4533-8147-923628f4a401
     */
    instanceId: string;

    /**
     * @type {string}
     * @memberof InlineResponse2011Class
     * @example unknown
     */
    source: string;
}
