/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReadMessageDto
 */
export interface ReadMessageDto {

    /**
     * @type {number}
     * @memberof ReadMessageDto
     */
    branchId: number;

    /**
     * @type {number}
     * @memberof ReadMessageDto
     */
    chatId?: number;

    /**
     * @type {number}
     * @memberof ReadMessageDto
     */
    cellphone?: number;
}
