/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2011Class } from './inline-response2011-class';
import { WhatsappChatDto } from './whatsapp-chat-dto';
 /**
 * 
 *
 * @export
 * @interface SendTextResponseDto
 */
export interface SendTextResponseDto {

    /**
     * @type {InlineResponse2011Class}
     * @memberof SendTextResponseDto
     */
    message: InlineResponse2011Class;

    /**
     * @type {WhatsappChatDto}
     * @memberof SendTextResponseDto
     */
    chat: WhatsappChatDto;
}
