/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SendTemplateDto } from './send-template-dto';
 /**
 * 
 *
 * @export
 * @interface SendTemplateDataDto
 */
export interface SendTemplateDataDto {

    /**
     * @type {SendTemplateDto}
     * @memberof SendTemplateDataDto
     */
    data: SendTemplateDto;

    /**
     * @type {number}
     * @memberof SendTemplateDataDto
     * @example 1
     */
    branchId: number;

    /**
     * @type {number}
     * @memberof SendTemplateDataDto
     * @example 1
     */
    leadId?: number;

    /**
     * @type {number}
     * @memberof SendTemplateDataDto
     * @example 1
     */
    sellerId?: number;
}
