/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SessionResponseDto } from './session-response-dto';
 /**
 * 
 *
 * @export
 * @interface SessionsResponseDataDto
 */
export interface SessionsResponseDataDto {

    /**
     * @type {Array<SessionResponseDto>}
     * @memberof SessionsResponseDataDto
     */
    data: Array<SessionResponseDto>;
}
