/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WhatsappMessageDto } from './whatsapp-message-dto';
 /**
 * 
 *
 * @export
 * @interface SessionResponseDto
 */
export interface SessionResponseDto {

    /**
     * @type {number}
     * @memberof SessionResponseDto
     * @example 23
     */
    id: number;

    /**
     * @type {string}
     * @memberof SessionResponseDto
     * @example b68ece44-0733-45bd-87e7-226880443623
     */
    sessionUuid: string;

    /**
     * @type {number}
     * @memberof SessionResponseDto
     * @example 23
     */
    messagesCount: number;

    /**
     * @type {Array<WhatsappMessageDto>}
     * @memberof SessionResponseDto
     */
    messages: Array<WhatsappMessageDto>;
}
