/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TokensDto
 */
export interface TokensDto {

    /**
     * @type {string}
     * @memberof TokensDto
     * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY3NjYwNTE3MywiZXhwIjoxNjc2NjA2MDczfQ.3WXwRPwFSf6jJQ_4WdWvUKSKiqjxLs1VoMHDQoEYfpU
     */
    accessToken: string;

    /**
     * @type {string}
     * @memberof TokensDto
     * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY3NjYwNTE3MywiZXhwIjoxNjc3MjA5OTczfQ._Hp6fTQEkttkgurDFKEV-luTtno_ocHyMiz04J4V1g0
     */
    refreshToken: string;
}
