/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserUpdatePasswordDto
 */
export interface UserUpdatePasswordDto {

    /**
     * @type {number}
     * @memberof UserUpdatePasswordDto
     * @example 15
     */
    userId: number;

    /**
     * @type {string}
     * @memberof UserUpdatePasswordDto
     * @example asfdF123**asdf
     */
    password: string;

    /**
     * @type {string}
     * @memberof UserUpdatePasswordDto
     * @example asfdF123**asdf
     */
    currentPassword: string;
}
