/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleDto } from './role-dto';
import { StatusDto } from './status-dto';
 /**
 * 
 *
 * @export
 * @interface UserDetailDto
 */
export interface UserDetailDto {

    /**
     * @type {number}
     * @memberof UserDetailDto
     * @example 1
     */
    id: number;

    /**
     * @type {string}
     * @memberof UserDetailDto
     * @example antonio@comino.com.ar
     */
    email: string;

    /**
     * @type {string}
     * @memberof UserDetailDto
     * @example 2024-11-15T16:15:25.715Z
     */
    latestLoginAt: string | null;

    /**
     * @type {StatusDto}
     * @memberof UserDetailDto
     */
    status: StatusDto;

    /**
     * @type {RoleDto}
     * @memberof UserDetailDto
     */
    role: RoleDto;
}
