/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WhatsappContactDto
 */
export interface WhatsappContactDto {

    /**
     * @type {number}
     * @memberof WhatsappContactDto
     * @example 23
     */
    id: number;

    /**
     * @type {string}
     * @memberof WhatsappContactDto
     * @example 23
     */
    phoneNumber: string;

    /**
     * @type {string}
     * @memberof WhatsappContactDto
     * @example 23
     */
    pushName: string;

    /**
     * @type {Array<string>}
     * @memberof WhatsappContactDto
     * @example 23
     */
    profilePicUrl: Array<string>;
}
