/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-bridge Node Api
 * The whatsapp-bridge API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WhatsappMessageFeedback
 */
export interface WhatsappMessageFeedback {

    /**
     * @type {boolean}
     * @memberof WhatsappMessageFeedback
     * @example true
     */
    isSent: boolean;

    /**
     * @type {boolean}
     * @memberof WhatsappMessageFeedback
     * @example false
     */
    isDelivered: boolean;

    /**
     * @type {boolean}
     * @memberof WhatsappMessageFeedback
     * @example false
     */
    isSeen: boolean;

    /**
     * @type {boolean}
     * @memberof WhatsappMessageFeedback
     * @example false
     */
    hasError: boolean;
}
